---
xp:
- phuongaz: 0
  idolbminh: 72
  quocthaiz: 0
  tpgbaker: 0
- phuongaz: 0
  idolbminh: 0
  quocthaiz: 0
  tpgbaker: 0
- phuongaz: 0
  idolbminh: 0
  quocthaiz: 0
  tpgbaker: 0
- phuongaz: 7
  idolbminh: 16
  quocthaiz: 7
  tpgbaker: 0
- phuongaz: 0
  idolbminh: 0
  quocthaiz: 0
  tpgbaker: 0
- phuongaz: 0
  idolbminh: 0
  quocthaiz: 0
  tpgbaker: 0
- phuongaz: 6
  idolbminh: 30
  quocthaiz: 0
  tpgbaker: 0
- phuongaz: 0
  idolbminh: 0
  quocthaiz: 0
  tpgbaker: 0
- phuongaz: 0
  idolbminh: 0
  quocthaiz: 0
  tpgbaker: 0
- phuongaz: 0
  idolbminh: 12
  quocthaiz: 4
  tpgbaker: 0
level:
- phuongaz: 1
  idolbminh: 1
  quocthaiz: 1
  tpgbaker: 1
- phuongaz: 1
  idolbminh: 1
  quocthaiz: 1
  tpgbaker: 1
- phuongaz: 1
  idolbminh: 1
  quocthaiz: 1
  tpgbaker: 1
- phuongaz: 1
  idolbminh: 1
  quocthaiz: 1
  tpgbaker: 1
- phuongaz: 1
  idolbminh: 1
  quocthaiz: 1
  tpgbaker: 1
- phuongaz: 1
  idolbminh: 1
  quocthaiz: 1
  tpgbaker: 1
- phuongaz: 1
  idolbminh: 1
  quocthaiz: 1
  tpgbaker: 1
- phuongaz: 1
  idolbminh: 1
  quocthaiz: 1
  tpgbaker: 1
- phuongaz: 1
  idolbminh: 1
  quocthaiz: 1
  tpgbaker: 1
- phuongaz: 1
  idolbminh: 1
  quocthaiz: 1
  tpgbaker: 1
...
